#!/bin/sh

# Exit script on errors
set -ue

# Load configuration file
if ! (source config.sh 2> /dev/null); then
  echo >&2 "Could not find $(dirname "$0")/config.sh"
  echo >&2 "Run $(dirname "$0")/configure to create it"
  exit 1
fi

# Create a temporary directory to store the repository
dir="$(mktemp -d)"

# Clone the repository (only need the most recent commit)
git clone --depth 1 "git@github.com:$owner/$repo" "$dir"

# Enter repository
cd "$dir"

# Rewrite $file with data from GitHub
echo "CONTRIBUTORS" > "$file"
curl "https://api.github.com/repos/$owner/$repo/contributors" |
  jq -r '.[].login | gsub( "^(?<d>.+)$"; "\(.d) - https://github.com/\(.d)")' >> "$file"

# Configure Git
git config user.name "$name"
git config user.email "$email"

# Commit and push change
# Will do nothing if there are no changes
git commit "$file" -m "$message"
git push origin HEAD
